// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

#ifndef PROTOBUF_meta_2eproto__INCLUDED
#define PROTOBUF_meta_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_meta_2eproto();
void protobuf_AssignDesc_meta_2eproto();
void protobuf_ShutdownFile_meta_2eproto();

class Package;

// ===================================================================

class Package : public ::google::protobuf::Message {
 public:
  Package();
  virtual ~Package();
  
  Package(const Package& from);
  
  inline Package& operator=(const Package& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Package& default_instance();
  
  void Swap(Package* other);
  
  // implements Message ----------------------------------------------
  
  Package* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Package& from);
  void MergeFrom(const Package& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string virtualPath = 1;
  inline bool has_virtualpath() const;
  inline void clear_virtualpath();
  static const int kVirtualPathFieldNumber = 1;
  inline const ::std::string& virtualpath() const;
  inline void set_virtualpath(const ::std::string& value);
  inline void set_virtualpath(const char* value);
  inline void set_virtualpath(const char* value, size_t size);
  inline ::std::string* mutable_virtualpath();
  
  // optional int32 num = 2;
  inline bool has_num() const;
  inline void clear_num();
  static const int kNumFieldNumber = 2;
  inline ::google::protobuf::int32 num() const;
  inline void set_num(::google::protobuf::int32 value);
  
  // optional string realFullPath = 3;
  inline bool has_realfullpath() const;
  inline void clear_realfullpath();
  static const int kRealFullPathFieldNumber = 3;
  inline const ::std::string& realfullpath() const;
  inline void set_realfullpath(const ::std::string& value);
  inline void set_realfullpath(const char* value);
  inline void set_realfullpath(const char* value, size_t size);
  inline ::std::string* mutable_realfullpath();
  
  // optional bool isDir = 24;
  inline bool has_isdir() const;
  inline void clear_isdir();
  static const int kIsDirFieldNumber = 24;
  inline bool isdir() const;
  inline void set_isdir(bool value);
  
  // repeated string listItem = 25;
  inline int listitem_size() const;
  inline void clear_listitem();
  static const int kListItemFieldNumber = 25;
  inline const ::std::string& listitem(int index) const;
  inline ::std::string* mutable_listitem(int index);
  inline void set_listitem(int index, const ::std::string& value);
  inline void set_listitem(int index, const char* value);
  inline void set_listitem(int index, const char* value, size_t size);
  inline ::std::string* add_listitem();
  inline void add_listitem(const ::std::string& value);
  inline void add_listitem(const char* value);
  inline void add_listitem(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& listitem() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_listitem();
  
  // optional int32 openMode = 26;
  inline bool has_openmode() const;
  inline void clear_openmode();
  static const int kOpenModeFieldNumber = 26;
  inline ::google::protobuf::int32 openmode() const;
  inline void set_openmode(::google::protobuf::int32 value);
  
  // optional int32 mode = 27;
  inline bool has_mode() const;
  inline void clear_mode();
  static const int kModeFieldNumber = 27;
  inline ::google::protobuf::int32 mode() const;
  inline void set_mode(::google::protobuf::int32 value);
  
  // optional int32 Operation = 8;
  inline bool has_operation() const;
  inline void clear_operation();
  static const int kOperationFieldNumber = 8;
  inline ::google::protobuf::int32 operation() const;
  inline void set_operation(::google::protobuf::int32 value);
  
  // optional int32 replicaNo = 9;
  inline bool has_replicano() const;
  inline void clear_replicano();
  static const int kReplicaNoFieldNumber = 9;
  inline ::google::protobuf::int32 replicano() const;
  inline void set_replicano(::google::protobuf::int32 value);
  
  // optional string opcode = 10;
  inline bool has_opcode() const;
  inline void clear_opcode();
  static const int kOpcodeFieldNumber = 10;
  inline const ::std::string& opcode() const;
  inline void set_opcode(const ::std::string& value);
  inline void set_opcode(const char* value);
  inline void set_opcode(const char* value, size_t size);
  inline ::std::string* mutable_opcode();
  
  // optional string rcode = 11;
  inline bool has_rcode() const;
  inline void clear_rcode();
  static const int kRcodeFieldNumber = 11;
  inline const ::std::string& rcode() const;
  inline void set_rcode(const ::std::string& value);
  inline void set_rcode(const char* value);
  inline void set_rcode(const char* value, size_t size);
  inline ::std::string* mutable_rcode();
  
  // optional uint32 migrateInst = 12;
  inline bool has_migrateinst() const;
  inline void clear_migrateinst();
  static const int kMigrateInstFieldNumber = 12;
  inline ::google::protobuf::uint32 migrateinst() const;
  inline void set_migrateinst(::google::protobuf::uint32 value);
  
  // optional bool uprange = 13;
  inline bool has_uprange() const;
  inline void clear_uprange();
  static const int kUprangeFieldNumber = 13;
  inline bool uprange() const;
  inline void set_uprange(bool value);
  
  // optional string sourceZHT = 14;
  inline bool has_sourcezht() const;
  inline void clear_sourcezht();
  static const int kSourceZHTFieldNumber = 14;
  inline const ::std::string& sourcezht() const;
  inline void set_sourcezht(const ::std::string& value);
  inline void set_sourcezht(const char* value);
  inline void set_sourcezht(const char* value, size_t size);
  inline ::std::string* mutable_sourcezht();
  
  // optional string targetZHT = 15;
  inline bool has_targetzht() const;
  inline void clear_targetzht();
  static const int kTargetZHTFieldNumber = 15;
  inline const ::std::string& targetzht() const;
  inline void set_targetzht(const ::std::string& value);
  inline void set_targetzht(const char* value);
  inline void set_targetzht(const char* value, size_t size);
  inline ::std::string* mutable_targetzht();
  
  // optional string rfname = 16;
  inline bool has_rfname() const;
  inline void clear_rfname();
  static const int kRfnameFieldNumber = 16;
  inline const ::std::string& rfname() const;
  inline void set_rfname(const ::std::string& value);
  inline void set_rfname(const char* value);
  inline void set_rfname(const char* value, size_t size);
  inline ::std::string* mutable_rfname();
  
  // optional string lfname = 17;
  inline bool has_lfname() const;
  inline void clear_lfname();
  static const int kLfnameFieldNumber = 17;
  inline const ::std::string& lfname() const;
  inline void set_lfname(const ::std::string& value);
  inline void set_lfname(const char* value);
  inline void set_lfname(const char* value, size_t size);
  inline ::std::string* mutable_lfname();
  
  // repeated uint64 migringpos = 18;
  inline int migringpos_size() const;
  inline void clear_migringpos();
  static const int kMigringposFieldNumber = 18;
  inline ::google::protobuf::uint64 migringpos(int index) const;
  inline void set_migringpos(int index, ::google::protobuf::uint64 value);
  inline void add_migringpos(::google::protobuf::uint64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      migringpos() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_migringpos();
  
  // optional string gmembership = 19;
  inline bool has_gmembership() const;
  inline void clear_gmembership();
  static const int kGmembershipFieldNumber = 19;
  inline const ::std::string& gmembership() const;
  inline void set_gmembership(const ::std::string& value);
  inline void set_gmembership(const char* value);
  inline void set_gmembership(const char* value, size_t size);
  inline ::std::string* mutable_gmembership();
  
  // optional bool isfwdmsg = 20;
  inline bool has_isfwdmsg() const;
  inline void clear_isfwdmsg();
  static const int kIsfwdmsgFieldNumber = 20;
  inline bool isfwdmsg() const;
  inline void set_isfwdmsg(bool value);
  
  // optional string asneighbor = 21;
  inline bool has_asneighbor() const;
  inline void clear_asneighbor();
  static const int kAsneighborFieldNumber = 21;
  inline const ::std::string& asneighbor() const;
  inline void set_asneighbor(const ::std::string& value);
  inline void set_asneighbor(const char* value);
  inline void set_asneighbor(const char* value, size_t size);
  inline ::std::string* mutable_asneighbor();
  
  // optional string wifecode = 22;
  inline bool has_wifecode() const;
  inline void clear_wifecode();
  static const int kWifecodeFieldNumber = 22;
  inline const ::std::string& wifecode() const;
  inline void set_wifecode(const ::std::string& value);
  inline void set_wifecode(const char* value);
  inline void set_wifecode(const char* value, size_t size);
  inline ::std::string* mutable_wifecode();
  
  // optional uint32 nummoves = 5;
  inline bool has_nummoves() const;
  inline void clear_nummoves();
  static const int kNummovesFieldNumber = 5;
  inline ::google::protobuf::uint32 nummoves() const;
  inline void set_nummoves(::google::protobuf::uint32 value);
  
  // optional string nodehistory = 4;
  inline bool has_nodehistory() const;
  inline void clear_nodehistory();
  static const int kNodehistoryFieldNumber = 4;
  inline const ::std::string& nodehistory() const;
  inline void set_nodehistory(const ::std::string& value);
  inline void set_nodehistory(const char* value);
  inline void set_nodehistory(const char* value, size_t size);
  inline ::std::string* mutable_nodehistory();
  
  // optional uint32 currnode = 6;
  inline bool has_currnode() const;
  inline void clear_currnode();
  static const int kCurrnodeFieldNumber = 6;
  inline ::google::protobuf::uint32 currnode() const;
  inline void set_currnode(::google::protobuf::uint32 value);
  
  // optional uint32 numwait = 7;
  inline bool has_numwait() const;
  inline void clear_numwait();
  static const int kNumwaitFieldNumber = 7;
  inline ::google::protobuf::uint32 numwait() const;
  inline void set_numwait(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:Package)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::std::string* virtualpath_;
  static const ::std::string _default_virtualpath_;
  ::google::protobuf::int32 num_;
  ::std::string* realfullpath_;
  static const ::std::string _default_realfullpath_;
  bool isdir_;
  ::google::protobuf::RepeatedPtrField< ::std::string> listitem_;
  ::google::protobuf::int32 openmode_;
  ::google::protobuf::int32 mode_;
  ::google::protobuf::int32 operation_;
  ::google::protobuf::int32 replicano_;
  ::std::string* opcode_;
  static const ::std::string _default_opcode_;
  ::std::string* rcode_;
  static const ::std::string _default_rcode_;
  ::google::protobuf::uint32 migrateinst_;
  bool uprange_;
  ::std::string* sourcezht_;
  static const ::std::string _default_sourcezht_;
  ::std::string* targetzht_;
  static const ::std::string _default_targetzht_;
  ::std::string* rfname_;
  static const ::std::string _default_rfname_;
  ::std::string* lfname_;
  static const ::std::string _default_lfname_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > migringpos_;
  ::std::string* gmembership_;
  static const ::std::string _default_gmembership_;
  bool isfwdmsg_;
  ::std::string* asneighbor_;
  static const ::std::string _default_asneighbor_;
  ::std::string* wifecode_;
  static const ::std::string _default_wifecode_;
  ::google::protobuf::uint32 nummoves_;
  ::std::string* nodehistory_;
  static const ::std::string _default_nodehistory_;
  ::google::protobuf::uint32 currnode_;
  ::google::protobuf::uint32 numwait_;
  friend void  protobuf_AddDesc_meta_2eproto();
  friend void protobuf_AssignDesc_meta_2eproto();
  friend void protobuf_ShutdownFile_meta_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(26 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Package* default_instance_;
};
// ===================================================================


// ===================================================================

// Package

// optional string virtualPath = 1;
inline bool Package::has_virtualpath() const {
  return _has_bit(0);
}
inline void Package::clear_virtualpath() {
  if (virtualpath_ != &_default_virtualpath_) {
    virtualpath_->clear();
  }
  _clear_bit(0);
}
inline const ::std::string& Package::virtualpath() const {
  return *virtualpath_;
}
inline void Package::set_virtualpath(const ::std::string& value) {
  _set_bit(0);
  if (virtualpath_ == &_default_virtualpath_) {
    virtualpath_ = new ::std::string;
  }
  virtualpath_->assign(value);
}
inline void Package::set_virtualpath(const char* value) {
  _set_bit(0);
  if (virtualpath_ == &_default_virtualpath_) {
    virtualpath_ = new ::std::string;
  }
  virtualpath_->assign(value);
}
inline void Package::set_virtualpath(const char* value, size_t size) {
  _set_bit(0);
  if (virtualpath_ == &_default_virtualpath_) {
    virtualpath_ = new ::std::string;
  }
  virtualpath_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Package::mutable_virtualpath() {
  _set_bit(0);
  if (virtualpath_ == &_default_virtualpath_) {
    virtualpath_ = new ::std::string;
  }
  return virtualpath_;
}

// optional int32 num = 2;
inline bool Package::has_num() const {
  return _has_bit(1);
}
inline void Package::clear_num() {
  num_ = 0;
  _clear_bit(1);
}
inline ::google::protobuf::int32 Package::num() const {
  return num_;
}
inline void Package::set_num(::google::protobuf::int32 value) {
  _set_bit(1);
  num_ = value;
}

// optional string realFullPath = 3;
inline bool Package::has_realfullpath() const {
  return _has_bit(2);
}
inline void Package::clear_realfullpath() {
  if (realfullpath_ != &_default_realfullpath_) {
    realfullpath_->clear();
  }
  _clear_bit(2);
}
inline const ::std::string& Package::realfullpath() const {
  return *realfullpath_;
}
inline void Package::set_realfullpath(const ::std::string& value) {
  _set_bit(2);
  if (realfullpath_ == &_default_realfullpath_) {
    realfullpath_ = new ::std::string;
  }
  realfullpath_->assign(value);
}
inline void Package::set_realfullpath(const char* value) {
  _set_bit(2);
  if (realfullpath_ == &_default_realfullpath_) {
    realfullpath_ = new ::std::string;
  }
  realfullpath_->assign(value);
}
inline void Package::set_realfullpath(const char* value, size_t size) {
  _set_bit(2);
  if (realfullpath_ == &_default_realfullpath_) {
    realfullpath_ = new ::std::string;
  }
  realfullpath_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Package::mutable_realfullpath() {
  _set_bit(2);
  if (realfullpath_ == &_default_realfullpath_) {
    realfullpath_ = new ::std::string;
  }
  return realfullpath_;
}

// optional bool isDir = 24;
inline bool Package::has_isdir() const {
  return _has_bit(3);
}
inline void Package::clear_isdir() {
  isdir_ = false;
  _clear_bit(3);
}
inline bool Package::isdir() const {
  return isdir_;
}
inline void Package::set_isdir(bool value) {
  _set_bit(3);
  isdir_ = value;
}

// repeated string listItem = 25;
inline int Package::listitem_size() const {
  return listitem_.size();
}
inline void Package::clear_listitem() {
  listitem_.Clear();
}
inline const ::std::string& Package::listitem(int index) const {
  return listitem_.Get(index);
}
inline ::std::string* Package::mutable_listitem(int index) {
  return listitem_.Mutable(index);
}
inline void Package::set_listitem(int index, const ::std::string& value) {
  listitem_.Mutable(index)->assign(value);
}
inline void Package::set_listitem(int index, const char* value) {
  listitem_.Mutable(index)->assign(value);
}
inline void Package::set_listitem(int index, const char* value, size_t size) {
  listitem_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Package::add_listitem() {
  return listitem_.Add();
}
inline void Package::add_listitem(const ::std::string& value) {
  listitem_.Add()->assign(value);
}
inline void Package::add_listitem(const char* value) {
  listitem_.Add()->assign(value);
}
inline void Package::add_listitem(const char* value, size_t size) {
  listitem_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
Package::listitem() const {
  return listitem_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
Package::mutable_listitem() {
  return &listitem_;
}

// optional int32 openMode = 26;
inline bool Package::has_openmode() const {
  return _has_bit(5);
}
inline void Package::clear_openmode() {
  openmode_ = 0;
  _clear_bit(5);
}
inline ::google::protobuf::int32 Package::openmode() const {
  return openmode_;
}
inline void Package::set_openmode(::google::protobuf::int32 value) {
  _set_bit(5);
  openmode_ = value;
}

// optional int32 mode = 27;
inline bool Package::has_mode() const {
  return _has_bit(6);
}
inline void Package::clear_mode() {
  mode_ = 0;
  _clear_bit(6);
}
inline ::google::protobuf::int32 Package::mode() const {
  return mode_;
}
inline void Package::set_mode(::google::protobuf::int32 value) {
  _set_bit(6);
  mode_ = value;
}

// optional int32 Operation = 8;
inline bool Package::has_operation() const {
  return _has_bit(7);
}
inline void Package::clear_operation() {
  operation_ = 0;
  _clear_bit(7);
}
inline ::google::protobuf::int32 Package::operation() const {
  return operation_;
}
inline void Package::set_operation(::google::protobuf::int32 value) {
  _set_bit(7);
  operation_ = value;
}

// optional int32 replicaNo = 9;
inline bool Package::has_replicano() const {
  return _has_bit(8);
}
inline void Package::clear_replicano() {
  replicano_ = 0;
  _clear_bit(8);
}
inline ::google::protobuf::int32 Package::replicano() const {
  return replicano_;
}
inline void Package::set_replicano(::google::protobuf::int32 value) {
  _set_bit(8);
  replicano_ = value;
}

// optional string opcode = 10;
inline bool Package::has_opcode() const {
  return _has_bit(9);
}
inline void Package::clear_opcode() {
  if (opcode_ != &_default_opcode_) {
    opcode_->clear();
  }
  _clear_bit(9);
}
inline const ::std::string& Package::opcode() const {
  return *opcode_;
}
inline void Package::set_opcode(const ::std::string& value) {
  _set_bit(9);
  if (opcode_ == &_default_opcode_) {
    opcode_ = new ::std::string;
  }
  opcode_->assign(value);
}
inline void Package::set_opcode(const char* value) {
  _set_bit(9);
  if (opcode_ == &_default_opcode_) {
    opcode_ = new ::std::string;
  }
  opcode_->assign(value);
}
inline void Package::set_opcode(const char* value, size_t size) {
  _set_bit(9);
  if (opcode_ == &_default_opcode_) {
    opcode_ = new ::std::string;
  }
  opcode_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Package::mutable_opcode() {
  _set_bit(9);
  if (opcode_ == &_default_opcode_) {
    opcode_ = new ::std::string;
  }
  return opcode_;
}

// optional string rcode = 11;
inline bool Package::has_rcode() const {
  return _has_bit(10);
}
inline void Package::clear_rcode() {
  if (rcode_ != &_default_rcode_) {
    rcode_->clear();
  }
  _clear_bit(10);
}
inline const ::std::string& Package::rcode() const {
  return *rcode_;
}
inline void Package::set_rcode(const ::std::string& value) {
  _set_bit(10);
  if (rcode_ == &_default_rcode_) {
    rcode_ = new ::std::string;
  }
  rcode_->assign(value);
}
inline void Package::set_rcode(const char* value) {
  _set_bit(10);
  if (rcode_ == &_default_rcode_) {
    rcode_ = new ::std::string;
  }
  rcode_->assign(value);
}
inline void Package::set_rcode(const char* value, size_t size) {
  _set_bit(10);
  if (rcode_ == &_default_rcode_) {
    rcode_ = new ::std::string;
  }
  rcode_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Package::mutable_rcode() {
  _set_bit(10);
  if (rcode_ == &_default_rcode_) {
    rcode_ = new ::std::string;
  }
  return rcode_;
}

// optional uint32 migrateInst = 12;
inline bool Package::has_migrateinst() const {
  return _has_bit(11);
}
inline void Package::clear_migrateinst() {
  migrateinst_ = 0u;
  _clear_bit(11);
}
inline ::google::protobuf::uint32 Package::migrateinst() const {
  return migrateinst_;
}
inline void Package::set_migrateinst(::google::protobuf::uint32 value) {
  _set_bit(11);
  migrateinst_ = value;
}

// optional bool uprange = 13;
inline bool Package::has_uprange() const {
  return _has_bit(12);
}
inline void Package::clear_uprange() {
  uprange_ = false;
  _clear_bit(12);
}
inline bool Package::uprange() const {
  return uprange_;
}
inline void Package::set_uprange(bool value) {
  _set_bit(12);
  uprange_ = value;
}

// optional string sourceZHT = 14;
inline bool Package::has_sourcezht() const {
  return _has_bit(13);
}
inline void Package::clear_sourcezht() {
  if (sourcezht_ != &_default_sourcezht_) {
    sourcezht_->clear();
  }
  _clear_bit(13);
}
inline const ::std::string& Package::sourcezht() const {
  return *sourcezht_;
}
inline void Package::set_sourcezht(const ::std::string& value) {
  _set_bit(13);
  if (sourcezht_ == &_default_sourcezht_) {
    sourcezht_ = new ::std::string;
  }
  sourcezht_->assign(value);
}
inline void Package::set_sourcezht(const char* value) {
  _set_bit(13);
  if (sourcezht_ == &_default_sourcezht_) {
    sourcezht_ = new ::std::string;
  }
  sourcezht_->assign(value);
}
inline void Package::set_sourcezht(const char* value, size_t size) {
  _set_bit(13);
  if (sourcezht_ == &_default_sourcezht_) {
    sourcezht_ = new ::std::string;
  }
  sourcezht_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Package::mutable_sourcezht() {
  _set_bit(13);
  if (sourcezht_ == &_default_sourcezht_) {
    sourcezht_ = new ::std::string;
  }
  return sourcezht_;
}

// optional string targetZHT = 15;
inline bool Package::has_targetzht() const {
  return _has_bit(14);
}
inline void Package::clear_targetzht() {
  if (targetzht_ != &_default_targetzht_) {
    targetzht_->clear();
  }
  _clear_bit(14);
}
inline const ::std::string& Package::targetzht() const {
  return *targetzht_;
}
inline void Package::set_targetzht(const ::std::string& value) {
  _set_bit(14);
  if (targetzht_ == &_default_targetzht_) {
    targetzht_ = new ::std::string;
  }
  targetzht_->assign(value);
}
inline void Package::set_targetzht(const char* value) {
  _set_bit(14);
  if (targetzht_ == &_default_targetzht_) {
    targetzht_ = new ::std::string;
  }
  targetzht_->assign(value);
}
inline void Package::set_targetzht(const char* value, size_t size) {
  _set_bit(14);
  if (targetzht_ == &_default_targetzht_) {
    targetzht_ = new ::std::string;
  }
  targetzht_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Package::mutable_targetzht() {
  _set_bit(14);
  if (targetzht_ == &_default_targetzht_) {
    targetzht_ = new ::std::string;
  }
  return targetzht_;
}

// optional string rfname = 16;
inline bool Package::has_rfname() const {
  return _has_bit(15);
}
inline void Package::clear_rfname() {
  if (rfname_ != &_default_rfname_) {
    rfname_->clear();
  }
  _clear_bit(15);
}
inline const ::std::string& Package::rfname() const {
  return *rfname_;
}
inline void Package::set_rfname(const ::std::string& value) {
  _set_bit(15);
  if (rfname_ == &_default_rfname_) {
    rfname_ = new ::std::string;
  }
  rfname_->assign(value);
}
inline void Package::set_rfname(const char* value) {
  _set_bit(15);
  if (rfname_ == &_default_rfname_) {
    rfname_ = new ::std::string;
  }
  rfname_->assign(value);
}
inline void Package::set_rfname(const char* value, size_t size) {
  _set_bit(15);
  if (rfname_ == &_default_rfname_) {
    rfname_ = new ::std::string;
  }
  rfname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Package::mutable_rfname() {
  _set_bit(15);
  if (rfname_ == &_default_rfname_) {
    rfname_ = new ::std::string;
  }
  return rfname_;
}

// optional string lfname = 17;
inline bool Package::has_lfname() const {
  return _has_bit(16);
}
inline void Package::clear_lfname() {
  if (lfname_ != &_default_lfname_) {
    lfname_->clear();
  }
  _clear_bit(16);
}
inline const ::std::string& Package::lfname() const {
  return *lfname_;
}
inline void Package::set_lfname(const ::std::string& value) {
  _set_bit(16);
  if (lfname_ == &_default_lfname_) {
    lfname_ = new ::std::string;
  }
  lfname_->assign(value);
}
inline void Package::set_lfname(const char* value) {
  _set_bit(16);
  if (lfname_ == &_default_lfname_) {
    lfname_ = new ::std::string;
  }
  lfname_->assign(value);
}
inline void Package::set_lfname(const char* value, size_t size) {
  _set_bit(16);
  if (lfname_ == &_default_lfname_) {
    lfname_ = new ::std::string;
  }
  lfname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Package::mutable_lfname() {
  _set_bit(16);
  if (lfname_ == &_default_lfname_) {
    lfname_ = new ::std::string;
  }
  return lfname_;
}

// repeated uint64 migringpos = 18;
inline int Package::migringpos_size() const {
  return migringpos_.size();
}
inline void Package::clear_migringpos() {
  migringpos_.Clear();
}
inline ::google::protobuf::uint64 Package::migringpos(int index) const {
  return migringpos_.Get(index);
}
inline void Package::set_migringpos(int index, ::google::protobuf::uint64 value) {
  migringpos_.Set(index, value);
}
inline void Package::add_migringpos(::google::protobuf::uint64 value) {
  migringpos_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
Package::migringpos() const {
  return migringpos_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
Package::mutable_migringpos() {
  return &migringpos_;
}

// optional string gmembership = 19;
inline bool Package::has_gmembership() const {
  return _has_bit(18);
}
inline void Package::clear_gmembership() {
  if (gmembership_ != &_default_gmembership_) {
    gmembership_->clear();
  }
  _clear_bit(18);
}
inline const ::std::string& Package::gmembership() const {
  return *gmembership_;
}
inline void Package::set_gmembership(const ::std::string& value) {
  _set_bit(18);
  if (gmembership_ == &_default_gmembership_) {
    gmembership_ = new ::std::string;
  }
  gmembership_->assign(value);
}
inline void Package::set_gmembership(const char* value) {
  _set_bit(18);
  if (gmembership_ == &_default_gmembership_) {
    gmembership_ = new ::std::string;
  }
  gmembership_->assign(value);
}
inline void Package::set_gmembership(const char* value, size_t size) {
  _set_bit(18);
  if (gmembership_ == &_default_gmembership_) {
    gmembership_ = new ::std::string;
  }
  gmembership_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Package::mutable_gmembership() {
  _set_bit(18);
  if (gmembership_ == &_default_gmembership_) {
    gmembership_ = new ::std::string;
  }
  return gmembership_;
}

// optional bool isfwdmsg = 20;
inline bool Package::has_isfwdmsg() const {
  return _has_bit(19);
}
inline void Package::clear_isfwdmsg() {
  isfwdmsg_ = false;
  _clear_bit(19);
}
inline bool Package::isfwdmsg() const {
  return isfwdmsg_;
}
inline void Package::set_isfwdmsg(bool value) {
  _set_bit(19);
  isfwdmsg_ = value;
}

// optional string asneighbor = 21;
inline bool Package::has_asneighbor() const {
  return _has_bit(20);
}
inline void Package::clear_asneighbor() {
  if (asneighbor_ != &_default_asneighbor_) {
    asneighbor_->clear();
  }
  _clear_bit(20);
}
inline const ::std::string& Package::asneighbor() const {
  return *asneighbor_;
}
inline void Package::set_asneighbor(const ::std::string& value) {
  _set_bit(20);
  if (asneighbor_ == &_default_asneighbor_) {
    asneighbor_ = new ::std::string;
  }
  asneighbor_->assign(value);
}
inline void Package::set_asneighbor(const char* value) {
  _set_bit(20);
  if (asneighbor_ == &_default_asneighbor_) {
    asneighbor_ = new ::std::string;
  }
  asneighbor_->assign(value);
}
inline void Package::set_asneighbor(const char* value, size_t size) {
  _set_bit(20);
  if (asneighbor_ == &_default_asneighbor_) {
    asneighbor_ = new ::std::string;
  }
  asneighbor_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Package::mutable_asneighbor() {
  _set_bit(20);
  if (asneighbor_ == &_default_asneighbor_) {
    asneighbor_ = new ::std::string;
  }
  return asneighbor_;
}

// optional string wifecode = 22;
inline bool Package::has_wifecode() const {
  return _has_bit(21);
}
inline void Package::clear_wifecode() {
  if (wifecode_ != &_default_wifecode_) {
    wifecode_->clear();
  }
  _clear_bit(21);
}
inline const ::std::string& Package::wifecode() const {
  return *wifecode_;
}
inline void Package::set_wifecode(const ::std::string& value) {
  _set_bit(21);
  if (wifecode_ == &_default_wifecode_) {
    wifecode_ = new ::std::string;
  }
  wifecode_->assign(value);
}
inline void Package::set_wifecode(const char* value) {
  _set_bit(21);
  if (wifecode_ == &_default_wifecode_) {
    wifecode_ = new ::std::string;
  }
  wifecode_->assign(value);
}
inline void Package::set_wifecode(const char* value, size_t size) {
  _set_bit(21);
  if (wifecode_ == &_default_wifecode_) {
    wifecode_ = new ::std::string;
  }
  wifecode_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Package::mutable_wifecode() {
  _set_bit(21);
  if (wifecode_ == &_default_wifecode_) {
    wifecode_ = new ::std::string;
  }
  return wifecode_;
}

// optional uint32 nummoves = 5;
inline bool Package::has_nummoves() const {
  return _has_bit(22);
}
inline void Package::clear_nummoves() {
  nummoves_ = 0u;
  _clear_bit(22);
}
inline ::google::protobuf::uint32 Package::nummoves() const {
  return nummoves_;
}
inline void Package::set_nummoves(::google::protobuf::uint32 value) {
  _set_bit(22);
  nummoves_ = value;
}

// optional string nodehistory = 4;
inline bool Package::has_nodehistory() const {
  return _has_bit(23);
}
inline void Package::clear_nodehistory() {
  if (nodehistory_ != &_default_nodehistory_) {
    nodehistory_->clear();
  }
  _clear_bit(23);
}
inline const ::std::string& Package::nodehistory() const {
  return *nodehistory_;
}
inline void Package::set_nodehistory(const ::std::string& value) {
  _set_bit(23);
  if (nodehistory_ == &_default_nodehistory_) {
    nodehistory_ = new ::std::string;
  }
  nodehistory_->assign(value);
}
inline void Package::set_nodehistory(const char* value) {
  _set_bit(23);
  if (nodehistory_ == &_default_nodehistory_) {
    nodehistory_ = new ::std::string;
  }
  nodehistory_->assign(value);
}
inline void Package::set_nodehistory(const char* value, size_t size) {
  _set_bit(23);
  if (nodehistory_ == &_default_nodehistory_) {
    nodehistory_ = new ::std::string;
  }
  nodehistory_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Package::mutable_nodehistory() {
  _set_bit(23);
  if (nodehistory_ == &_default_nodehistory_) {
    nodehistory_ = new ::std::string;
  }
  return nodehistory_;
}

// optional uint32 currnode = 6;
inline bool Package::has_currnode() const {
  return _has_bit(24);
}
inline void Package::clear_currnode() {
  currnode_ = 0u;
  _clear_bit(24);
}
inline ::google::protobuf::uint32 Package::currnode() const {
  return currnode_;
}
inline void Package::set_currnode(::google::protobuf::uint32 value) {
  _set_bit(24);
  currnode_ = value;
}

// optional uint32 numwait = 7;
inline bool Package::has_numwait() const {
  return _has_bit(25);
}
inline void Package::clear_numwait() {
  numwait_ = 0u;
  _clear_bit(25);
}
inline ::google::protobuf::uint32 Package::numwait() const {
  return numwait_;
}
inline void Package::set_numwait(::google::protobuf::uint32 value) {
  _set_bit(25);
  numwait_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_meta_2eproto__INCLUDED
